### ISSUE TITLE
Cannot add/remove courses to/from the sidebar

### ISSUE THREAD

**Issue by luciencd** [luciencd/suggestr#4]
Cannot add courses to sidebar, there is a javascript error.
Cannot remove courses from sidebar, there is a javascript error.

Uncaught SyntaxError: Unexpected token <n.parseJSON @ jquery.js:7522getAjaxStatus @ universalFunctions.js:89(anonymous function) @ (index):139j @ jquery.js:3099k.fireWith @ jquery.js:3211x @ jquery.js:8264(anonymous function) @ jquery.js:8605

Happens when you click the buttons "add" and "ignore".

**Comment by bennyty** [comment]
Can you provide some more information such as what the error is?

**Comment by luciencd** [comment]
Session_id Cookie does not stay set from templating.php.

**Comment by luciencd** [comment]
There are two issues at play: sessionid cookie being set after it is needed. It is set in templating.php but is needed in the home.php file.

Second issue: in home.htm, in the JavaScript functions that call .post calls on the Ajaxcontrollers, it always returns "sorry there was an error". In the newest controller addtag it doesn't even do that. It doesn't return any getajaxerror(d) .
