### ISSUE TITLE
Color scheme.

### ISSUE THREAD

**Issue by luciencd** [luciencd/suggestr#6]
<img width="1349" alt="screenshot 2015-12-29 20 27 24" src="https://cloud.githubusercontent.com/assets/5478880/12045100/e8d3800e-ae6a-11e5-8407-e6a0c830243c.png">

Does this color scheme look good to people? I'm trying to decide exactly how it will look and I need second opinions. I went with a "sandy" background for the classes. But it looks a bit awkward with the big green, blue, red, and gray buttons. 

Thoughts? I attached a screenie.

**Comment by bennyty** [comment]
I always thought the button colors (default from bootstrap) were too bold.

**Comment by bennyty** [comment]
Our design has moved on from the colorscheme so other issues cover this one now.
