### ISSUE TITLE
how to make suggestr.co the default url for our website?

### ISSUE THREAD

**Issue by luciencd** [luciencd/suggestr#77]

**Comment by leopoldjoy** [comment]
@luciencd @bennyty Here's are the steps to setup the Namecheap domain with Bluemix:
1. Configure the domain as a route inside the Bluemix dashboard.
2. Locate the IP address of the Bluemix server and add it as an "A record" to the Namecheap domain. Here is a [screenshot](http://imgur.com/4Cwm3QR) of what the Namecheap configuration should look like once the IP has been added.

Let me know if you have any questions.

**Comment by luciencd** [comment]
It works!
I had to follow this tutorial: https://www.ibm.com/developerworks/community/blogs/c1b14989-1f61-4411-a56c-abcde2481218/entry/How_To_Custom_and_Apex_Root_Domains_on_Bluemix?lang=en
